name: flutter_ecommpay_core
description: A new Flutter plugin project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ecommpay_core_ios: 
    git: "https://github.com/lifeapps-42/flutter_ecommpay_core_ios"
  flutter_ecommpay_core_platform_interface: 
    git: "https://github.com/lifeapps-42/flutter_ecommpay_core_platform_interface"
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      ios:
        default_package: flutter_ecommpay_core_ios
    

